[package]
name = "dioxus_rig_app"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow-array = { version = "57.3.0", optional = true }
arrow-schema = { version = "57.3.0", optional = true }
dioxus = { version = "0.7.7", features = ["router", "fullstack"] }
futures = { version = "0.3.32", optional = true }
lancedb = { version = "0.27.2", optional = true }
rig-core = { version = "0.36.0", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.1", features = ["full"], optional = true }
uuid = { version = "1.23.1", features = ["v4"], optional = true }

[features]
default = ["web", "server"]
web = ["dioxus/web"]
server = [
    "dioxus/server", 
    "dep:rig-core", 
    "dep:tokio", 
    "dep:lancedb", 
    "dep:arrow-array", 
    "dep:arrow-schema", 
    "dep:uuid", 
    "dep:futures"
]
