[application]
# App (Project) Name
name = "dioxus_rig_app"
# Dioxus app title
default_title = "Agent Maker"
# App id (for macOS and Android)
app_id = "com.dioxus.rig"

[web.app]
# HTML title tag content
title = "Agent Maker"

